.TH "RBT::mini_rbt" 3 "2023年 十月 24日 星期二" "Version 1.0.0" "miniRBT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RBT::mini_rbt \- 机械臂多线程的入口函数  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mini_rbt\&.h>\fP
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBmini_rbt\fP ()"
.br
.ti -1c
.RI "\fB~mini_rbt\fP ()"
.br
.ti -1c
.RI "void \fBrbt_begin\fP ()"
.br
.RI "多线程人物开始运行的函数 "
.in -1c
.SS "Public 属性"

.in +1c
.ti -1c
.RI "pthread_t \fBethercat_thread\fP"
.br
.ti -1c
.RI "pthread_t \fBkin_thread\fP"
.br
.in -1c
.SH "详细描述"
.PP 
机械臂多线程的入口函数 
.SH "构造及析构函数说明"
.PP 
.SS "RBT::mini_rbt::mini_rbt ()"

.SS "RBT::mini_rbt::~mini_rbt ()"

.SH "成员函数说明"
.PP 
.SS "void RBT::mini_rbt::rbt_begin ()"

.PP
多线程人物开始运行的函数 
.SH "类成员变量说明"
.PP 
.SS "pthread_t RBT::mini_rbt::ethercat_thread"

.SS "pthread_t RBT::mini_rbt::kin_thread"


.SH "作者"
.PP 
由 Doyxgen 通过分析 miniRBT 的 源代码自动生成\&.
