.TH "include/rbt_model.h" 3 "2023年 十月 25日 星期三" "Version 1.0.0" "miniRBT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/rbt_model.h
.SH SYNOPSIS
.br
.PP
\fC#include <QObject>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'rbt_trajectory\&.h'\fP
.br

.SS "类"

.in +1c
.ti -1c
.RI "struct \fBDH_Parameter\fP"
.br
.RI "kin & dyn model "
.ti -1c
.RI "class \fBRBT::Model_Base\fP"
.br
.RI "机械臂运动学和动力学的基类，包含了一些位姿变换的计算 "
.ti -1c
.RI "class \fBRBT::Rbt_Model\fP"
.br
.RI "机械臂运动学类，包含了一些位姿变换的计算，继承于Model_Base "
.in -1c
.SS "命名空间"

.in +1c
.ti -1c
.RI " \fBRBT\fP"
.br
.in -1c
.SH "作者"
.PP 
由 Doyxgen 通过分析 miniRBT 的 源代码自动生成\&.
