.TH "rbt_pdo" 3 "2023年 十月 23日 星期一" "Version 1.0.0" "miniRBT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rbt_pdo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rbt_ethercat\&.h>\fP
.SS "Public 属性"

.in +1c
.ti -1c
.RI "unsigned int \fBOperation_Mode\fP"
.br
.ti -1c
.RI "unsigned int \fBOperation_Mode_Display\fP"
.br
.ti -1c
.RI "unsigned int \fBTarget_Position\fP"
.br
.ti -1c
.RI "unsigned int \fBActual_Position\fP"
.br
.ti -1c
.RI "unsigned int \fBControl_Word\fP"
.br
.ti -1c
.RI "unsigned int \fBStatus_Word\fP"
.br
.ti -1c
.RI "unsigned int \fBPosition_Offset\fP"
.br
.in -1c
.SH "类成员变量说明"
.PP 
.SS "unsigned int rbt_pdo::Actual_Position"

.SS "unsigned int rbt_pdo::Control_Word"

.SS "unsigned int rbt_pdo::Operation_Mode"

.SS "unsigned int rbt_pdo::Operation_Mode_Display"

.SS "unsigned int rbt_pdo::Position_Offset"

.SS "unsigned int rbt_pdo::Status_Word"

.SS "unsigned int rbt_pdo::Target_Position"


.SH "作者"
.PP 
由 Doyxgen 通过分析 miniRBT 的 源代码自动生成\&.
