.TH "include/rbt_ethercat.h" 3 "2023年 十月 24日 星期二" "Version 1.0.0" "miniRBT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/rbt_ethercat.h
.SH SYNOPSIS
.br
.PP
\fC#include <errno\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <sys/resource\&.h>\fP
.br
\fC#include <sys/time\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <sys/mman\&.h>\fP
.br
\fC#include <malloc\&.h>\fP
.br
\fC#include <sched\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'ecrt\&.h'\fP
.br
\fC#include 'rbt_variable\&.h'\fP
.br

.SS "类"

.in +1c
.ti -1c
.RI "struct \fBrbt_pdo\fP"
.br
.ti -1c
.RI "class \fBRBT::Ethercat\fP"
.br
.RI "etherca主站类，包含ethercat主站设置操作和通信操作 "
.in -1c
.SS "命名空间"

.in +1c
.ti -1c
.RI " \fBRBT\fP"
.br
.in -1c
.SH "作者"
.PP 
由 Doyxgen 通过分析 miniRBT 的 源代码自动生成\&.
